name: Playwright Tests
on:
  workflow_dispatch:
  pull_request:
    branches: main
env:
  PASSWORD: ${{ secrets.PASSWORD }}
  TEST_MODE: 'full'
jobs:
  chromium:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        run: npm run pw:chromium
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-chromium
          path: tests/playwright-report/
          retention-days: 30
  firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps firefox
      - name: Run Playwright tests
        run: npm run pw:firefox
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-firefox
          path: tests/playwright-report/
          retention-days: 30
  webkit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps webkit
      - name: Run Playwright tests
        run: npm run pw:webkit
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-webkit
          path: tests/playwright-report/
          retention-days: 30
